### ISSUE TITLE
Forward declarations removed after transpiling

### ISSUE THREAD

**Issue by ppietrasa** [specs-feup/clava#10]
One of the things I noticed after transpiling.

Forward declarations get removed.

SomeHeader.h:
```
-class SomeClass;
```

**Comment by joaobispo** [comment]
Sorry, I could not replicate this problem. I've created a header file with just the code `class SomeClass;`, and after parsing I've obtained something like:

```
#ifndef _CLAVA_ISSUE10_H_
#define _CLAVA_ISSUE10_H_


class SomeClass;

#endif
```

Could you provide an example? (e.g., zip file with source, LARA script, and configuration)

**Comment by ppietrasa** [comment]
I guess it has something to do with namespaces. It seems only the forward declarations defined in global namespace survive.

C++ Input:
```
#include <iostream>

class ForwardDeclClass1;

namespace a {
   class ForwardDeclClass2;
   class RegularClass1 {};
   namespace b {
      class ForwardDeclClass3;
      class RegularClass2 {};
      namespace c {
         class ForwardDeclClass4;
         class RegularClass3 {};
      }
   }
}

int main(int argc, char *argv[]){
   std::cout << "Hello World!" << std::endl;
   return 0;
}
```

LARA script:
```
aspectdef TouchMeAspect
   select vardecl end
   apply
      setName('a_' + $vardecl.name);
   end
end
```

After clava compilation:
```
#include <iostream>

class ForwardDeclClass1;


namespace a {
   
   class RegularClass1 {
      
   };
   
   
   namespace b {
      
      class RegularClass2 {
         
      };
      
      
      namespace c {
         
         class RegularClass3 {
            
         };
      
      }
   
   }

}

int main(int a_argc, char *a_argv[]) {
   std::cout << "Hello World!" << std::endl;
   
   return 0;
}
```

**Comment by joaobispo** [comment]
The Clang-based dumper was ignoring all declarations inside namespace declarations that did not have definitions. To fix this, now the dumper ignores declarations that are implicit (i.e., are not present in source code).

**Comment by ppietrasa** [comment]
Thanks!

**Comment by ppietrasa** [comment]
I just retested.

This still doesn't work for me. However, I see your fix in the git log along with the unit test.
So maybe its on my side now. Perhaps something is cached or so. How could I run the ClavaWeaver's unit tests?

**Comment by ppietrasa** [comment]
After you updated the issue #15. I ran my test for this issue again. This time it worked.

**Comment by joaobispo** [comment]
The problem was related to the Ubuntu version of the precompiled executable of the dumper, which did not contain the fix (probably other versions, besides the Windows version, also did not contain the fix). After issue #15 the dumper was updated again and incorporated the fix.
