### ISSUE TITLE
Miscompilation of Nested Anonymous C Structs

### ISSUE THREAD

**Issue by CharlesLoveman** [specs-feup/clava#100]
Translating the following C program splits the anonymous struct declaration into two declarations. I don't think it is valid C to declare a new struct type inside a struct, unless it is part of a variable declaration.
```
// Source
struct foo {
    struct {
        int x;
    } a;
};

int main() {
    return 0;
}
```

```
// Result
struct foo {

   struct anon_testFoo_c_2 {
      int x;
   };

   struct anon_testFoo_c_2 a;
};

int main() {

   return 0;
}
```

Compiling the resulting program using clang outputs a warning
```
testResult.c:3:4: warning: declaration does not declare anything [-Wmissing-declarations]
   struct anon_testFoo_c_2 {
   ^
1 warning generated.
```

**Comment by joaobispo** [comment]
Hello Charles, thank you for creating the issue.

The current output you show is a result, in part, of how Clang represents this code in the AST. However, I think this can be fixed, next week we will have a look at it.

**Comment by joaobispo** [comment]
@CharlesLoveman A new fix was pushed into the main branch, please check if it is ok now.

**Comment by CharlesLoveman** [comment]
Yes that works great, thanks for fixing it.
