### ISSUE TITLE
Miscompilation of escape sequence in c string literal.

### ISSUE THREAD

**Issue by CharlesLoveman** [specs-feup/clava#102]
A string literal in a c program with escape sequences such as `"\xFF"` will be translated into a unicode character.
The program
```
int main() {
    char bom[] = "\xFF\xFE";
    return 0;
}
```
compiles to 
```
int main() {
   char bom[3] = "ÿþ";

   return 0;
}
```

**Comment by joaobispo** [comment]
Thanks for the issue, it should be solved now.
