### ISSUE TITLE
C++ app stops compiling after going through Clava, with no transformations

### ISSUE THREAD

**Issue by tiagolascasas** [specs-feup/clava#106]
This C++ application compiles without issue on its own, but after going through Clava it fails to compile. Nothing is done to the code, other than the default Clava tasks (i.e., preprocessor, conversion to AST and code generation). C++11 and C++17 were both considered, and both led to similar results.

The problem was first identified by Clava's CMake extension reporting error code 2, which indicates failure. On further inspection (i.e., compiling the woven code directly with g++), we can find several errors in file Image.h. These errors do not exist in the original code, and g++ is capable of compiling it without any issue.

Reproduce with the attached files and instructions. 

[template_issue.zip](https://github.com/specs-feup/clava/files/9760673/template_issue.zip)

**Comment by lm-sousa** [comment]
@tiagolascasas Is this issue still valid?

**Comment by lm-sousa** [comment]
Closing as stale.
