### ISSUE TITLE
Operator signatures broken after transpiling

### ISSUE THREAD

**Issue by ppietrasa** [specs-feup/clava#11]
One of the things I noticed after transpiling.

The operator:
```
operator bool() const {
```
becomes

```
bool operator bool() const {
```

and operator:
```
operator T*() const {
```

becomes
```
T * operator type-parameter-0-0 *() const {
```
g++ later complains, e.g.:

```
error: return type specified for ‘operator bool’
```

**Comment by joaobispo** [comment]
CXXConversionDecl was using the code generation method of CXXMethodDecl, after overriding the method this was fixed.

**Comment by ppietrasa** [comment]
The return type has disappeared. Great!
I'm closing this.

BTW. There's still an issue with "type-parameter-0-0".  However, the example I've given is incomplete and the issue deserves its own ticket anyway. So I am going to open one and provide the details there.
