### ISSUE TITLE
Comments at end of line or interspersed between tokens not recognized

### ISSUE THREAD

**Issue by ppietrasa** [specs-feup/clava#12]
One more issue.

In Code

```
/* multline
   commet
*/

// single line comment
class Dog { // comment at EOL
   private:
/* comment starts a line */ std::string name;
   public:
/* comment 1 */      Dog() /* comment 2 */ : name("Hektor") {} /* comment 3 */
[..]
```

The  "comment at EOL", "comment 2", and "comment 3" are not selectable in LARA.
These also get dropped after transpiling. 

P.S. I also saw some cases, where although not selectable, the comments somehow survived. I don't know what circumstances may cause the difference.

**Comment by joaobispo** [comment]
Regarding the comments, the smallest granularity where you can insert/select comments in the Clava AST is at the statement level. Comments that are between expressions are "pulled out" to the corresponding statement.

When parsing with Clang most comments are removed from the AST, we are reinserting them manually in a post-processing step. Although we try to maintain some similarity between the generated code and the original source code, our focus is on having functionally equivalent code.

A reason for this decision is that approaches for source-to-source transformations that directly modify the source code text buffer (e.g., Clang's Rewriter) will always have an advantage with regard to preserving the original source code. However, if you need to implement a sequence of complex, chained transformations, you will most likely have to reparse the modified code many times (in the worst case, every time you change something), to the point of becoming impractical in certain situations.

Clava uses an alternative, complementary approach where you can apply the modifications directly over the AST, and in the end, generate the code. If a LARA script modifies the code, you can think of it as a compilation pass done at the source level, immediately before feeding the source code to a compiler (e.g., gcc, Clang).

**Comment by joaobispo** [comment]
I'm closing this issue, as it refers to features that are not planned to be implemented (correctly supporting comments with granularity below the statement).

**Comment by ppietrasa** [comment]
Strange. I thought I commented and closed this already. Anyway, thanks for clarifying!
