### ISSUE TITLE
If's then and else nodes may be omitted

### ISSUE THREAD

**Issue by Goncalerta** [specs-feup/clava#142]
There is a potential error either in clava itself or in the TypeScript interface:
Given an `If` joinpoint, the `$if.then` and `$if.else` have a return type of `Scope`, but the following code:

```typescript
if (1) a; else b;
if (1) {} else {}
if (1) ; else ;
```

When run in a script:

```typescript
console.log("then", $if?.then?.constructor?.name);
console.log("else", $if?.else?.constructor?.name);
```

Returns:

```
then Body
else Body
then Body
else Body
then undefined
else undefined
```

This means that either the third `if` should have a block with `EmptyStmt`, or the return type should be `Scope | undefined`.

**Comment by joaobispo** [comment]
Upon closer inspection, what was happening was that Clang's AST structure seems identical for both `if(1) ; else ;` and `if(1) ;`, that is, NullStmt is both representing the absence of an `else`, and an `else` with an empty statement. The same for the `if`, but the `then` is not optional.

Both situations can be distinguished by checking the location of the NullStmt, if it is an empty statement, the location will be valid.

Code like below:

```c
if (1) a; else b;
if (1) {} else {}
if (1) ; else ;
if(1) ;
```

Will now generate exactly the same code, and applying the script should output the following:

```
then Body
else Body
then Body
else Body
then Body
else Body
then Body
else undefined
```

Please test it and close the issue if this is solved.

**Comment by Goncalerta** [comment]
One issue with the `if(1) ;` case if that `$if.else` is defined to return a `Scope`, at least in typescript. If returning `undefined` is desirable in the absence of an else block, then the return value should be changed to `Scope | undefined`.
Alternatively, a dummy empy Body could be created for the else, although that could be undesirable because we might want to distinguish empty elses from no else.

**Comment by Goncalerta** [comment]
Just tested it and it works as intended. Now it would be nice to update else's return type.
