### ISSUE TITLE
Question: Javascript modules in LARA

### ISSUE THREAD

**Issue by ppietrasa** [specs-feup/clava#16]
Hi João,

Is it possible to import/load external javascript module from within a LARA file?

Alternatively, I see LARA supports cmd() for invoking shell commands.
Can I somehow capture the output of cmd() into a variable?

Thanks
Piotr

**Comment by joaobispo** [comment]
Hello,

currently it is possible to load JavaScript files when Clava starts. If you use the `-i` flag, you can indicate a list of folders, separated by `;`, and all .js files inside the folder will be loaded automatically (this is not recursive).

About invoking shell commands, I recommend using the class `ProcessExecutor`, from the [LARA API](http://specs.fe.up.pt/tools/clava/doc/). You need to import it, create an instance, and invoke the command with the function `.execute()`. After execution, the instance will contain information about the execution. Example:

```
import lara.util.ProcessExecutor;

aspectdef Test

   var executor = new ProcessExecutor();
   executor.execute("ls", "-l");
   println(executor.getConsoleOutput());

end
```

Please refer to the documentation if you want more details about the functionalities of ProcessExecutor.

**Comment by joaobispo** [comment]
Additionally, I've just enabled all privileges for the GraalVM JS engine (which is the one used by default by Clava), so that you can use the function `load()`. More details [here](https://www.graalvm.org/reference-manual/js/JavaScriptCompatibility/#global-properties).

**Comment by ppietrasa** [comment]
Question answered.
I find your comments very informative. Thank you.
