### ISSUE TITLE
C style typedef-enum inside a class mistranslated

### ISSUE THREAD

**Issue by ppietrasa** [specs-feup/clava#17]
The code
```
class Klass  {
   typedef enum {
      value1,
      value2,
   } EnumType;
}; 
```

translates to
```
class Klass {

   enum Klass::EnumType {
      value1,
      value2,
   };

   typedef enum Klass::EnumType EnumType;
};
```

which later fails to compile with:
```
error: ‘EnumType’ does not name an enumeration in ‘Klass’
```
on this line: ```enum Klass::EnumType {```

**Comment by joaobispo** [comment]
After parsing, Clang separates "inlined" typedefs of 'tag' types (structs/enums) in the declaration of the 'tag' type and the typedef. Clava was not giving a name to anonymous enums, originating the error in this issue. Now it should generate code like this:

```
class Klass {
   
   enum anon_clava_issue17_cpp_2 {
      value1,
      value2,
   };
   
   typedef enum anon_clava_issue17_cpp_2 AnEnum;
};
```

**Comment by ppietrasa** [comment]
Thanks. The fix helps.
