### ISSUE TITLE
Value initialization issue is back again

### ISSUE THREAD

**Issue by ppietrasa** [specs-feup/clava#20]
This is issue #9 manifesting itself again, though it has been fixed.

I noticed that ClungAstDumper has been updated recently. Could this be the reason behind the regression?

I tried downgrading to v4.2.13, 4.2.12, 4.2.11 by checking out the old state or by tuning
 ClangAstParser/src/pt/up/fe/specs/clang/ClangAstWebResource.java, but didn't have much success. Hmm..

**Comment by ppietrasa** [comment]
To workaround my problems I tried this approach:

```
--- a/ClavaAst/src/pt/up/fe/specs/clava/ast/decl/data/ctorinit/AnyMemberInit.java
+++ b/ClavaAst/src/pt/up/fe/specs/clava/ast/decl/data/ctorinit/AnyMemberInit.java
@@ -20,6 +20,8 @@ import pt.up.fe.specs.clava.ast.decl.CXXConstructorDecl;
 import pt.up.fe.specs.clava.ast.decl.Decl;
 import pt.up.fe.specs.clava.ast.decl.FieldDecl;
 
+import pt.up.fe.specs.clava.ast.expr.CXXConstructExpr;
+
 public class AnyMemberInit extends CXXCtorInitializer {
 
     /// DATAKEYS BEGIN
@@ -45,7 +47,13 @@ public class AnyMemberInit extends CXXCtorInitializer {
         // System.out.println("DATA: " + get(INIT_EXPR));
         // System.out.println(
         // "ANY_MEMBER: " + get(ANY_MEMBER_DECL).get(FieldDecl.DECL_NAME) + "(" + get(INIT_EXPR).getCode() + ")");
-
+        boolean canUseValueInitialization = false;
+        if (get(INIT_EXPR) instanceof CXXConstructExpr) {
+            canUseValueInitialization = ((CXXConstructExpr) get(INIT_EXPR)).getArgs().isEmpty();
+        }
+        if(canUseValueInitialization) {
+            return get(ANY_MEMBER_DECL).get(FieldDecl.DECL_NAME) + "()";
+        }
         return get(ANY_MEMBER_DECL).get(FieldDecl.DECL_NAME) + "(" + get(INIT_EXPR).getCode() + ")";
     }
 }
```

This handles some edge cases better, where explicit invocation of constructor (ala issue #9 fix) won't work. Example:
```

#include <netinet/in.h>


class NetKlass {
  public:
     NetKlass() : m_sockAddr() {}
  private:
     struct sockaddr m_sockAddr;
};
```

I didn't notice any side effects this approach on my code. However, I did not run the unit tests. I still haven't learned how.

**Comment by joaobispo** [comment]
Thanks for the suggestion, I've added a fix based on your code.

Regarding running the unit tests, how are you compiling the code, loading the project in Eclipse, or running the eclipse-build tool?

**Comment by ppietrasa** [comment]
Thanks!

Regarding unit tests. I am using the eclipse-build tool from the command line.

**Comment by joaobispo** [comment]
I've updated the eclipse-build tool, and now supports the flag `--test`, which after compiling the projects, executes the unit tests.

The tool looks for classes whose names end in "...Test", and considers that those classes have JUnit tests inside. The tool will generate an ANT HTML report in a `reports` folder where the tool is executed.

**Comment by ppietrasa** [comment]
Thanks! This is good news. I'll give it a try on the next opportunity.

**Comment by joaobispo** [comment]
Closing this issue.
