### ISSUE TITLE
Selecting return statments in Clava/Lara

### ISSUE THREAD

**Issue by jdeters** [specs-feup/clava#3]
I'm trying to use Clava and Lara to create instrumentation for my program. There's instrumentation that I would like to do right _before_ the function returns. Inserting advice after the function body is pretty straight forward, however I have yet to find any documentation on Lara that shows how one would apply advice _right before_ the return statement.

Is this currently possible to do with Clava/Lara?

**Comment by cc187** [comment]
It is possible to insert your code right before the return points of a function (return statements and the end of the body). The `function` join point has a specific action for that, `insertReturn`. 

The documentation for this action is:
`joinpoint insertReturn(joinpoint code)`
`joinpoint insertReturn(String code)`
>Inserts the joinpoint/string before the return points of the function (return statements and implicitly, at the end of the function)

Here is a simple example showing how to use it:
```
aspectdef InsertReturnExample
    select function end
    apply
        $function.exec insertReturn('// code to insert');
    end
end
```

**Comment by jdeters** [comment]
This is extremely helpful! Thank you!

**Comment by joaobispo** [comment]
It was previously possible to apply advice right before the return statement, but in an undocumented, discouraged way.

We have just added a new join point, `returnStmt`, which can be used to directly select return statements:

```
aspectdef ReturnStmtExample
    select returnStmt end
    apply
        println("Return: " + $returnStmt.location);
    end
end
```
