### ISSUE TITLE
Enhance `if` and `for` dump when missing block statement

### ISSUE THREAD

**Issue by fabiodrg** [specs-feup/clava#30]
I noticed that when `if` or `for` statements are one-liners, i.e., they lack the block with the brackets `{...}`, Clava does not change line and indent the descendant statement. This results in weird formatting and perhaps can be improved.

Original code:
```
if(A == 0.0) {
        printf("With block");
}

if(A == 0.0)
    printf("Oneline");

for (i = 0; i < NI; i++)
    for (j = 0; j < NJ; j++) {
        C[i * NJ + j] = 0.0;
        for (k = 0; k < NK; ++k)
            C[i * NJ + j] += A[i * NK + k] * B[k * NJ + j];
    }
```

Clava output:
```
if(A == 0.0) {
      printf("With scope/block");
}
// Note: if without block, everything on the same line
if(A[1] == 0.0) printf("Oneline if statement");
// Second for statement, same line as first for statement
for(i = 0; i < 1024; i++) for(j = 0; j < 1024; j++) {
  C[i * 1024 + j] = 0.0;
  // inner most for, everything on the same line
  for(k = 0; k < 1024; ++k) C[i * 1024 + j] += A[i * 1024 + k] * B[k * 1024 + j];
}
```

Especially for deeply nested `for` statements, if they all miss the block, it will look ugly! I think it would be safe to change line, add indentation and then the single statement.

After inspecting the AST for all presented cases, it seems `If` and `For` statements nodes have a descendant node `CompoundStmt`, which is likely the body. If it lacks the block `{...}`, it has an attribute `isNaked` set to `true`. Perhaps, this information could be used when dumping this node? And this probably solves all possible scenarios (whiles, etc).

**Comment by joaobispo** [comment]
I think this [commit](https://github.com/specs-feup/clava/commit/a0e09c3994b4db7841c1fdbaf7603b61d8e619b0) solves this issue.

**Comment by fabiodrg** [comment]
Yes, good job :smile:
