### ISSUE TITLE
Inconsistent behaviour in operators joinpoint's `type` attribute

### ISSUE THREAD

**Issue by fabiodrg** [specs-feup/clava#31]
Consider the following code:

```c
typedef double MY_TYPE;
void ops() {
    MY_TYPE a, b, c;

    a = a + b + c;
    a += b + c;
}
```

The datatype of all operators involved is a typedef, `MY_TYPE` which in turn is a primitive `double`. Now consider the following LARA excerpt:

```js
var $func = Query.search("function", {name: "ops"}).getFirst();
for (var $op of Query.searchFrom($func, "op")) {
    println($op.code + " => " + $op.kind + ":" + $op.type);
}
```

Output:
```
a = a + b + c => assign:Joinpoint 'typedefType'
a + b + c => add:Joinpoint 'builtinType'
a + b => add:Joinpoint 'builtinType'
a += b + c => add_assign:Joinpoint 'typedefType'
b + c => add:Joinpoint 'builtinType
```

**Problem:** Operators such as addition, multiply, etc. have a type attribute which is an instance of `builtinType`. However, the assignment operators (`=`, `+=`, ...) have a type attribute instance of `typedefType`. Notice that all operands are of type `MY_TYPE`.

I consider this to be inconsistent. It's quite handy to be possible to unroll a type definition until we get a primitive type, but for that, there's a `desugar` and `desugarAll`, with the latter being useful for e.g. nested typedefs. I think there are two possible approaches:
1. the `type` attribute references the original type, as is in the original code. In case people need to get the primitive, use the existing desugared options.
2. most of the time people want the primitive anyway, therefore make the `type` equivalent to `desugarAll` and add a new attribute where is possible to reach the original type. Deprecate existing `desugar*` attributes to avoid confusion.

Regardless of the approach, I would imagine this could break existing code. Perhaps, could be an opportunity to rename the attribute? I always thought the `type` attribute in all joinpoints would return the class type or something because of its presence in all joinpoints and not all of them have a notion of data type. Perhaps, `dataType` would be easier to understand? Also, in the UI, `type` is an attribute that returns `joinpoint`. Shouldn't it be an instance of `type` joinpoint?

I couldn't figure out why the behaviour is different across different operators. Both assign and math operators share the class `pt.up.fe.specs.clava.ast.expr.BinaryOperator`, and I couldn't spot anything wrong around here.

**Comment by joaobispo** [comment]
The .type attribute is a global attribute, for certain nodes it has meaning, for others it does not (returns undefined in that case).

Most of the time, what type is returned is defined by Clang, this returns the same type as the type associated in the corresponding Clang AST (there are a few exceptions, such as $function and $call).

Due to this attribute being widely used in LARA code, changes to what it returns has the potential to break code, a new attribute would be recommended.

The return type of $type should be 'type' and not 'joinpoint'
