### ISSUE TITLE
Template specialization is not supported

### ISSUE THREAD

**Issue by mcfx** [specs-feup/clava#39]
Hi, I'm using Clava these days, it's very useful, thanks for your work.

When I'm trying to work with some code which has template specialization, Clava gives me wrong results. (See the example below)

I guess this is not implemented yet, and I'm wondering whether it's in your roadmap. Thanks.

The code below is from https://en.cppreference.com/w/cpp/language/template_specialization
```cpp
#include <iostream>
template<typename T>   // primary template
struct is_void : std::false_type
{
};
template<>  // explicit specialization for T = void
struct is_void<void> : std::true_type
{
};
int main()
{
    // for any type T other than void, the 
    // class is derived from false_type
    std::cout << is_void<char>::value << '\n'; 
    // but when T is void, the class is derived
    // from true_type
    std::cout << is_void<void>::value << '\n';
}
```

After `println($program.code)` in Clava, it becomes
```cpp
/**** File 'test.cpp' ****/

#include <iostream>
template <typename T>
struct is_void : std::false_type {

};

struct is_void : std::true_type { // explicit specialization for T = void

};
int main() {
   // for any type T other than void, the
   // class is derived from false_type
   std::cout << is_void<char>::value << '\n';
   // but when T is void, the class is derived
   // from true_type
   std::cout << is_void<void>::value << '\n';
}

/**** End File ****/
```

which is not compilable.

**Comment by joaobispo** [comment]
Hello @mcfx, thanks for pointing this out. In fact, code generation for template specialization was not implemented yet, and the node was using the code generation method of a super class.

I've implemented code generation for this node, and the example you show should now pass. I did not test additional cases, so it might need more work for more complicated cases.

As an aside, I checked the [repository](https://github.com/mcfx/cplib) where you are using Clava, I might have some tips and questions for you, if you are interested please contact me (my email is on my GitHub profile).
