### ISSUE TITLE
New illegal reflective access operation warnings after update

### ISSUE THREAD

**Issue by jdeters** [specs-feup/clava#4]
I just updated Clava with the update script. When I run my build now, I get the following warning:

> WARNING: An illegal reflective access operation has occurred
> WARNING: Illegal reflective access by com.thoughtworks.xstream.core.util.Fields (file:/home/justin/Research/CilkAspects/clava/Clava/ClavaWeaver_lib/xstream-jar-1.4.8.jar) to field java.util.TreeMap.comparator
> WARNING: Please consider reporting this to the maintainers of com.thoughtworks.xstream.core.util.Fields
> WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
> WARNING: All illegal access operations will be denied in a future release

**Comment by joaobispo** [comment]
For now, this warning is harmless.

It originates from an external dependency, XStream, which we use to read/write XML files. After Java 9, certain things this library did became illegal.

We are aware of this problem, and periodically we check if there is a solution for it.

**Comment by joaobispo** [comment]
This should be fixed now
