### ISSUE TITLE
[LARAC] Add the ability of converting LARA-style imports to JS-style ones.

### ISSUE THREAD

**Issue by lm-sousa** [specs-feup/clava#42]
LARAC currently creates a massive file with all the contents of all .lara files and then converts it to JS.
Add the option of converting a single .lara file to a .js file including its import statements.

**Comment by joaobispo** [comment]
I consider that this issue is currently solved. The single JS file is no longer generated, and imports in .lara files are transformed into calls to the JS function laraImport(), which loads each file separately.
