### ISSUE TITLE
Make the behavior of imports between js and lara files uniform

### ISSUE THREAD

**Issue by Sleepy105** [specs-feup/clava#49]
js files are automatically imported (unless the folder name is src-lara)
lara files need to be manually imported

This creates conflicts with hybrid modules (source in js, imports of Clava modules in lara) because js files get imported again creating errors.

**Comment by joaobispo** [comment]
This issue has been resolved for all LARA compilers, with this [commit](https://github.com/specs-feup/lara-framework/commit/16a84146b2364b0786f90d63e82df530cee66852) in lara-framework.
