### ISSUE TITLE
Passing multiple folders to -ih

### ISSUE THREAD

**Issue by aubertc** [specs-feup/clava#59]
I apologize if my question is very naïve but I could not figure out the following.

The doc reads:

> -ih,--includes-headers <dir1[,dir2]*> 

If I want to include two folders (say, `headers/` and `utilities/`), what is the correct command?

I have tried

- `-ih "utilities , headers"`
- `-ih "utilities/ , headers/" `
- ` -ih utilities/,headers/`
- `-ih utilities/, headers/`
- `-ih utilities, headers`
- `-ih utilities , headers`
- `-ih utilities -ih headers`
- `-ih utilities/ -ih headers/`

But none of those work. What am I missing?

**Comment by joaobispo** [comment]
Sorry, the documentation is incorrect, the separator is `;`. I've update the documentation for the next release.

**Comment by aubertc** [comment]
Thanks!

However, I still can't make it work… Isn't `-ih ../headers/;../utilities/` the appropriate syntax?

**Comment by aubertc** [comment]
Ah, ok, you need quotes, it's ` -ih "../headers/;../utilities/"`.
