### ISSUE TITLE
Build of ClavaWeaver not working

### ISSUE THREAD

**Issue by ppietrasa** [specs-feup/clava#6]
The final 'create_jar' target fails.

Running:

`$ java -jar eclipse-build.jar --config https://raw.githubusercontent.com/specs-feup/clava/master/ClavaWeaver/eclipse.build`

Results in:

```
[ANT]:Finished target 'create_jar'
Exception in thread "main" /home/piotr/work/clavaw/ClavaWeaver/jar.xml:8: Problem creating jar: archive contains more than 65535 entries.
```

Possible solution would be to tune the generated jar.xml file:

```
++ ../jar.xml	2020-11-19 12:11:26.145314275 +0100
@@ -5,13 +5,13 @@
 	<!--ANT 1.7 is required  -->
 	 <!-- <target name="create_jar" depends="compile_ClavaWeaver"> -->
 	 <target name="create_jar">
-	    <jar destfile="ClavaWeaver.jar" filesetmanifest="mergewithoutmain">
+	    <jar destfile="ClavaWeaver.jar" zip64Mode="always" filesetmanifest="mergewithoutmain">
```

See this StackOverflow question:
https://stackoverflow.com/questions/39524481/error-creating-jar-archive-contains-more-than-65535-entries

**Comment by joaobispo** [comment]
I've just updated eclipse-build.jar to include the modification you suggested, please download it again and check if the problem is solved.

**Comment by ppietrasa** [comment]
That was quick. Thanks!!

**Comment by ppietrasa** [comment]
And yes I checked it and it worked.
