### ISSUE TITLE
[ClavaWeaver] Test failures due to local path dependence in ClavaWeaverRunner

### ISSUE THREAD

**Issue by joaonmatos** [specs-feup/clava#60]
The tests at [cxxweaver.ClavaWeaverRunner](https://github.com/specs-feup/clava/blob/1fefb072ef1bfa9195913e3eea02a16ad6b7e779/ClavaWeaver/test/pt/up/fe/specs/cxxweaver/ClavaWeaverRunner.java) are consistently failing due to loading files of the type `"C:\\Users\\JoaoBispo\\Desktop\\shared\\clava-tests\\Tests\\2017-09_lara_resource\\resource_example.clava"`. Are these files checked into the repository? Should they be using relative links?

**Comment by joaobispo** [comment]
File was removed.
