### ISSUE TITLE
[ClavaWeaver] CMaker test fails instead of skipping when optional cmake dependency is not 

### ISSUE THREAD

**Issue by joaonmatos** [specs-feup/clava#64]
The following test, when `cmake` is not present on the computer, fails:

https://github.com/specs-feup/clava/blob/f9acbf769c15bd2d3c0a3b89cb6464efdc474ee0/ClavaWeaver/test/pt/up/fe/specs/cxxweaver/tests/CxxApiTest.java#L73

This specification is a bit inconsistent. If the CMake dependency is considered to be mandatory, then it would make most sense to test that the aspect works in the presence and fails in the absence of CMake. However, I would consider CMake to be optional and recommend that the test checks for the presence of CMake, and skips if it is not present.

**Comment by lm-sousa** [comment]
@joaobispo Is this still valid?
