### ISSUE TITLE
Clava Tool: Redirect console.log and related methods

### ISSUE THREAD

**Issue by joaonmatos** [specs-feup/clava#77]
Currently, console.log and other similar methods are not showing up in the console output of the Clava tool web app.

What is happening to that output? Blackholed? Spamming logs?

Redirection should be set up for console methods as well. Perhaps using the `out`, `err`, `in` options of the Truffle context API? https://www.graalvm.org/truffle/javadoc/org/graalvm/polyglot/Context.Builder.html

**Comment by lm-sousa** [comment]
When you are talking about "Clava console output" are you referring to the output window in the Clava UI or in the terminal when executing Clava without the UI?

**Comment by lm-sousa** [comment]
Sometimes I forget that even exists... We need to have tags/labels for bug reports.

**Comment by lm-sousa** [comment]
Solved with the changes introduced in specs-feup/lara-framework#33 and specs-feup/specs-java-libs#9
