### ISSUE TITLE
Initializer with an empty set of parentheses - miscompiled

### ISSUE THREAD

**Issue by ppietrasa** [specs-feup/clava#9]
Given this C++ input:

```
class Color {};


class Cat
{
  public:
    Cat() : m_age(5), m_color()
    {
    }

    void miau(int times);

  private:
    unsigned int m_age;
    Color m_color;
};
```

And a simple LARA,  the contents of which seem not to matter as long as it changes/touches the input file in some way, e.g.:

```
aspectdef DeclReplacer
  select vardecl end
  apply
      setName('VARREPL_' + $vardecl.name);
  end
end
```

I get the following CLAVA compilation result:
```
#ifndef _CAT_H_
#define _CAT_H_


class Color {
   
};


class Cat {
   
   
   public:
   Cat() : m_age(5), m_color(Color) {
   }
   
   void miau(int VARREPL_times);
   
   
   private:
   unsigned int m_age;
   Color m_color;
};

#endif
```

Note the default constructor's initialization list. The:

```
Cat() : m_age(5), m_color()
```

becomes

```
Cat() : m_age(5), m_color(Color)
```

The empty initializer `m_color()` is replaced with `m_color(Color)`. This is incorrect C++ and does not compile.

Yeah,  i could remove the value initialization attempt from the input. But we want CLAVA to improve ;-)

**Comment by joaobispo** [comment]
What is happening here is that when parsing the code, Clang adds a node representing the implicit constructor that is being called by m_color().

From the information I can obtain from Clang (both for [Expr](https://clang.llvm.org/doxygen/classclang_1_1Expr.html) and [CXXConstructExpr](https://clang.llvm.org/doxygen/classclang_1_1CXXConstructExpr.html) nodes) I could not figure out how to determine if the constructor should be omitted or not (e.g., omit if not present in the original source code).

Instead, now I am using the property `requiresZeroInitialization`. If true, adds parenthesis to the code generated for the constructor  (e.g., `m_color(Color())`).

I've updated both the source code and the compiled version with this fix.

**Comment by ppietrasa** [comment]
Thank you! I'll give it a try tomorrow and likely close the issue.

**Comment by ppietrasa** [comment]
OK. Closing
